USE DATABASE PBIHealthCheck;
USE SCHEMA JobData;
USE WAREHOUSE pbi_healthcheck;

INSERT INTO PBIHealthCheck.JobData.POWERBI_QAS_ELIGIBLE
select
'QAS',
PBI.Session_id,
PBI.QUERY_ID
from PBIHealthCheck.JobData.POWERBI_CUSTOMER_HEALTH_CHECKS PBI
join SNOWFLAKE.ACCOUNT_USAGE.QUERY_ACCELERATION_ELIGIBLE QAE on QAE.QUERY_ID=PBI.QUERY_ID;


select * from PBIHealthCheck.JobData.POWERBI_QAS_ELIGIBLE;